# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6173c63bae28e8abd251081cc91d84542b90e760e61ce8108237a200da592fb2d0defb20da1ac84354111660f555d503422463c0e25cf595be10462181b84d4c

test:
  secret_key_base: 7e584a8ec889dce36d47e0751bed911d193798af7af56bfa12a31c3a11fc261d2ecc94efad5aa5cd9da69fe553226ef11463fcbcf18cfcfe62c0a97b15ef75db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
